# This is a basic workflow

name: Upload Friend Kernel

on:
  workflow_dispatch:

jobs:
  upload_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Git
        run: |
          git config --global user.name "PeterSuh-Q3"
          git config --global user.email dante9000@gmail.com
          
      - name: copy friend kernel to repo
        run: |
          #echo "Param1: ${{ github.event.client_payload.param1 }}"
          ROOT_PATH=${{ github.workspace }}
          cd ${ROOT_PATH}/
          URLS=$(curl -k -s https://api.github.com/repos/PeterSuh-Q3/tcrpfriend/releases/latest | jq -r ".assets[].browser_download_url")
          for file in $URLS; do curl --insecure --location --progress-bar "$file" -O; done          

      - name: Commit and push changes
        run: |
          git add .
          git commit -a -m "upload lastest"
          git push            
