# This is a basic workflow

name: Upload Friend Kernel

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  upload_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Git
        run: |
          git config --global user.name "PeterSuh-Q3"
          git config --global user.email dante9000@gmail.com
          
      - name: copy friend kernel to repo
        run: |
          #echo "Param1: ${{ github.event.client_payload.param1 }}"
          ROOT_PATH=${{ github.workspace }}
          cd ${ROOT_PATH}/
          cp /opt/output/bzImage-friend .
          cp /opt/output/initrd-friend .
          cp /opt/output/chksum .

      - name: Commit and push changes
        run: |
          git add .
          git commit -a -m "upload lastest"
          git push            
